name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - testing-ci-cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build the application
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t spring-boot-tdd-app:latest .
          docker tag spring-boot-tdd-app:latest ${{ secrets.DOCKER_USERNAME }}/spring-boot-tdd-app:latest
          docker tag spring-boot-tdd-app:latest ${{ secrets.DOCKER_USERNAME }}/spring-boot-tdd-app:${{ github.run_id }}

      # Step 6: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker Image to DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-tdd-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-tdd-app:${{ github.run_id }}

      # Step 8: Run the container (without port forwarding)
      - name: Run Container
        run: |
          docker run -d \
            --name spring-boot-tdd-app-${{ github.run_id }} \
            ${{ secrets.DOCKER_USERNAME }}/spring-boot-tdd-app:${{ github.run_id }}

      # Step 9: Test the running container (inside the container via docker exec)
      - name: Test Container
        run: |
          echo "Testing container endpoint http://localhost:8080/greet/hello/name (inside container)..."
          # We'll retry a few times in case the app needs a few seconds to start
          for i in {1..2}; do
            # Check if the container responds with HTTP 200 (success)
            STATUS=$(docker exec spring-boot-tdd-app-${{ github.run_id }} \
              curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/greet/hello/name || true)

            if [ "$STATUS" = "200" ]; then
              echo "✅ Container responded with 200!"
              exit 0
            else
              echo "Got HTTP status: $STATUS. Waiting 5s before retry..."
              sleep 5
            fi
          done

          echo "❌ Container did not respond with 200 after multiple attempts."
          exit 1

      # Step 10: Remove Old Containers
      - name: Remove Old Containers
        run: |
          docker ps -a --filter "name=spring-boot-tdd-app-" --format "{{.ID}} {{.Names}}" \
            | grep -v "spring-boot-tdd-app-${{ github.run_id }}" \
            | awk '{print $1}' \
            | xargs -r docker rm -f

      # Step 11: Remove Local Docker Images (optional)
      - name: Remove Local Docker Images
        run: |
          docker rmi spring-boot-tdd-app:latest || true
          docker image prune -f
